# Generated by Django 5.0.6 on 2024-06-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scolorship',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('fn', models.CharField(max_length=23)),
                ('mn', models.CharField(max_length=23)),
                ('ln', models.CharField(max_length=23)),
                ('address', models.CharField(max_length=34)),
                ('mob', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('pc', models.ImageField(upload_to='profiles/')),
            ],
        ),
    ]
