# Generated by Django 5.0.6 on 2024-06-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scolorship',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='scolorship',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='scolorship',
            old_name='dob',
            new_name='Date_Of_Birth',
        ),
        migrations.RenameField(
            model_name='scolorship',
            old_name='fn',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='scolorship',
            old_name='ln',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='scolorship',
            old_name='mn',
            new_name='Middle_Name',
        ),
        migrations.RenameField(
            model_name='scolorship',
            old_name='mob',
            new_name='Mobile_NO',
        ),
        migrations.RenameField(
            model_name='scolorship',
            old_name='pc',
            new_name='Profile_Picture',
        ),
    ]
